version: "0.0.28"

services:
  app_proxy:
    environment:
      APP_HOST: btfs_server_1
      APP_PORT: 5001 #BTFS API port

  server:
    image: simbadmarino/btfs-node:v3.3.0@sha256:fd0e9720b3eb372e32553e05e837e6ab53e959cf32986c2042e9b541364e2b4f
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    #command: >
    # btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"http://127.0.0.1:5001\",\"http://umbrel.local\"]' && btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"PUT\",\"GET\",\"POST\"]'"
    environment:
      BTFS_PATH: "/data/.btfs"
      BTFS_LOGGING: ""
